config:
  backup: false
  banner: true
  create: true
  dotpath: ../dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: true
  import_variables:
  - variables.yaml
  import_actions:
  - actions.yaml
dotfiles:
profiles:
